branches:
  only:
    - master
    - master-v3
language: objective-c
os: osx
osx_image: xcode7
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
  matrix:
    - TEST_TYPE=ios
    - TEST_TYPE=podspecs
script:
- |
    if [ "$TEST_TYPE" = ios ]; then
      set -o pipefail
      xcodebuild test -workspace ParseFacebookUtils.xcworkspace -sdk iphonesimulator -scheme ParseFacebookUtilsV4-iOS -configuration Debug -destination "platform=iOS Simulator,name=iPhone 4s" -destination "platform=iOS Simulator,name=iPhone 6 Plus" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty
    elif [ "$TEST_TYPE" = podspecs ]; then
      pod lib lint ParseFacebookUtilsV4.podspec
      pod lib lint --use-libraries ParseFacebookUtilsV4.podspec
    fi
after_success:
- |
    if [ "$TEST_TYPE" = ios ]; then
      bash <(curl -s https://codecov.io/bash)
    fi
